// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../entity/history_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2149668090923161415),
    name: 'HistoryItem',
    lastPropertyId: const obx_int.IdUid(9, 3462868628393728729),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5019587804338794865),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1794655708039552948),
        name: 'unixTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4559836914936397878),
        name: 'contents',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6014255297227825112),
        name: 'format',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5213659044146009160),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4053612569362177365),
        name: 'errorLevel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2409988678925015809),
        name: 'origin',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8996910725043469129),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3462868628393728729),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2149668090923161415),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    HistoryItem: obx_int.EntityDefinition<HistoryItem>(
      model: _entities[0],
      toOneRelations: (HistoryItem object) => [],
      toManyRelations: (HistoryItem object) => {},
      getId: (HistoryItem object) => object.id,
      setId: (HistoryItem object, int id) {
        object.id = id;
      },
      objectToFB: (HistoryItem object, fb.Builder fbb) {
        final contentsOffset = fbb.writeString(object.contents);
        final formatOffset = fbb.writeString(object.format);
        final typeOffset = fbb.writeString(object.type);
        final errorLevelOffset = fbb.writeString(object.errorLevel);
        final originOffset = fbb.writeString(object.origin);
        final notesOffset = fbb.writeString(object.notes);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.unixTime);
        fbb.addOffset(2, contentsOffset);
        fbb.addOffset(3, formatOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addOffset(5, errorLevelOffset);
        fbb.addOffset(6, originOffset);
        fbb.addBool(7, object.isFavorite);
        fbb.addOffset(8, notesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final unixTimeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final contentsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final formatParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final errorLevelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final originParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = HistoryItem(
          unixTime: unixTimeParam,
          contents: contentsParam,
          format: formatParam,
          type: typeParam,
          errorLevel: errorLevelParam,
          origin: originParam,
          isFavorite: isFavoriteParam,
          notes: notesParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HistoryItem] entity fields to define ObjectBox queries.
class HistoryItem_ {
  /// See [HistoryItem.id].
  static final id = obx.QueryIntegerProperty<HistoryItem>(
    _entities[0].properties[0],
  );

  /// See [HistoryItem.unixTime].
  static final unixTime = obx.QueryIntegerProperty<HistoryItem>(
    _entities[0].properties[1],
  );

  /// See [HistoryItem.contents].
  static final contents = obx.QueryStringProperty<HistoryItem>(
    _entities[0].properties[2],
  );

  /// See [HistoryItem.format].
  static final format = obx.QueryStringProperty<HistoryItem>(
    _entities[0].properties[3],
  );

  /// See [HistoryItem.type].
  static final type = obx.QueryStringProperty<HistoryItem>(
    _entities[0].properties[4],
  );

  /// See [HistoryItem.errorLevel].
  static final errorLevel = obx.QueryStringProperty<HistoryItem>(
    _entities[0].properties[5],
  );

  /// See [HistoryItem.origin].
  static final origin = obx.QueryStringProperty<HistoryItem>(
    _entities[0].properties[6],
  );

  /// See [HistoryItem.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<HistoryItem>(
    _entities[0].properties[7],
  );

  /// See [HistoryItem.notes].
  static final notes = obx.QueryStringProperty<HistoryItem>(
    _entities[0].properties[8],
  );
}
